
variables:
   GIT_SUBMODULE_STRATEGY: normal


stages:
  - stage_rtl
  - stage_fpga

rtl_sim:
  before_script:
    - export PATH=/usr/bin:$PATH
    - export PATH=/opt/iverilog/git/2018.11.09/bin:$PATH
    - export PATH=/opt/gnu-mcu-eclipse/riscv-none-gcc/8.1.0-2-20181019-0952/bin:$PATH
  stage: stage_rtl
  script:
    - make -C ci run_gpio_toggle


fpga:
  before_script:
    - source /opt/Xilinx/Vivado/2018.2/settings64.sh
  stage: stage_fpga
  script:
    - make -C synt/fpga synt
  tags:
    - vivado


