language: c

before_install:
    - sudo apt-get install -y build-essential iverilog

script:
  - make -C sim/verilog compile

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c678e77ac4a8af897f6b
    on_success: change  
    on_failure: always  
    on_start: never     
  
  
  
  

  
