language: c

git:
  submodules: false


before_install:
  - git submodule update --init
  - sudo apt-get install -y build-essential iverilog

script:
  - cd sim && ./runtest.py  --buildonly  ../ctests/gpio_toggle -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c678e77ac4a8af897f6b
    on_success: change  
    on_failure: always  
    on_start: never     
  
  
  
  

  
